# Generated by Django 4.1.7 on 2023-03-25 04:14

from django.db import migrations, models

# def create_data(apps, schema_editor):
#     Shape = apps.get_model('shapes', 'Shape')
#     Shape(dimensionValue=5).save()

class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('shapes'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionValue', models.IntegerField()),
            ],
        ),
        # migrations.RunPython(create_data),
    ]

    # operations = [
    #     migrations.RunPython(create_data),
    # ]
