# Generated by Django 4.1 on 2023-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometricCanvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionValue', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shapes',
        ),
    ]
